FROM python:alpine

WORKDIR /app

COPY ../requirements.txt ./

RUN pip install -r ./requirements.txt

COPY ../api/ ./api/

CMD [ "fastapi", "dev", "./api/main.py", "--host", "0.0.0.0", "--port", "8000"]